name: hw1_env
dependencies:
  - python=3.8
  - pip
  - pip:
      - numpy==1.20.2
      - pandas==1.2.4
      - matplotlib==3.5.1
      - torch==1.11.0
      - scikit-learn==1.0.2
      - shap==0.40.0
      - scipy==1.8.0
      - seaborn==0.11.1
      - plotly== #TODO
      - imblearn== #TODO
      - wandb==#TODO
<<<<<<< Updated upstream
      - statsmodels== #TODO??
=======
      - xgboost== #TODO
      - shap== #TODO

>>>>>>> Stashed changes


